# TODO: deploys the pods but launcher complains: [1,0]<stderr>:FileNotFoundError: [Errno 2] No such file or directory: 'train_3d.list'

apiVersion: kubeflow.org/v1alpha2
kind: MPIJob
metadata:
  labels:
    app: eleescan-3dgan
  name: train-mpijob
spec:
  slotsPerWorker: 1
  cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          hostNetwork: true
          containers:
          - image: cernefp/custom_mpi_learn # gitlab-registry.cern.ch/cloud-infrastructure/gpu-mpi-containers/mpi_learn # use here my custom image tor testing: aws-cli with --no-sign-request to the public CERN s3 bucket with the GAN data
            imagePullPolicy: Always
            securityContext:
              privileged: true
            name: train-mpijob
            resources:
              limits:
                nvidia.com/gpu: 1
            command: ["/bin/sh","-c"]
            args:
            - mpirun -tag-output -x LD_LIBRARY_PATH -x PATH -x TERM=linux -x GANINMEM=/tmp/gan_data -x USES3=1 -x NCCL_DEBUG=INFO -x NCCL_SOCKET_IFNAME=eth0 -mca pml ob1 -mca btl ^openib python3 MPIGDriver.py bb.json train_3d.list test_3d.list --tf --epochs 1 --features-name X --labels-name y --easgd --worker-opt rmsprop &&
              tail -f /dev/null
            volumeMounts:
            - name: train-list
              mountPath: "/mpi_learn/train_3d.list"
              subPath: "train_3d.list"
            - name: test-list
              mountPath: "/mpi_learn/test_3d.list"
              subPath: "test_3d.list"
          volumes:
          - name: test-list
            configMap:
              name: 3dgan-datafile-lists
              items:
              - key: "test_3d.list"
                path: "test_3d.list"
          - name: train-list
            configMap:
              name: 3dgan-datafile-lists
              items:
              - key: "train_3d.list"
                path: "train_3d.list"
    Worker: # TODO: add mounts to workers too? this fixed the "train_3d.list not found" error but now complains a python script can't find .h5 file. Adding the mpirun cmd here generates the error "ORTE does not know how to route a message to the specified daemon"
      replicas: 2
      template:
        spec:
          containers:
          - image: cernefp/custom_mpi_learn
            name: train-mpijob
            resources:
              limits:
                nvidia.com/gpu: 1
            volumeMounts:
            - name: train-list
              mountPath: "/mpi_learn/train_3d.list"
              subPath: "train_3d.list"
            - name: test-list
              mountPath: "/mpi_learn/test_3d.list"
              subPath: "test_3d.list"
          volumes:
          - name: test-list
            configMap:
              name: 3dgan-datafile-lists
              items:
              - key: "test_3d.list"
                path: "test_3d.list"
          - name: train-list
            configMap:
              name: 3dgan-datafile-lists
              items:
              - key: "train_3d.list"
                path: "train_3d.list"
#backoffLimit: 12
